version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: platziblog
    ports:
      - "3306:3306"
    volumes:
      - platziblog:/var/lib/mysql
volumes:
  platziblog:

